Inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [

	path('dashboard/', views.DashBoard, name='dashboard'),

	path('brand/add/', views.AddBrand, name='brand'),
	path('brand/', views.AllBrand, name='all_brand'),
	path('brand/update/<int:brand_id>/', views.UpdateBrand, name='update_brand'),
	path('brand/delete/<int:brand_id>/', views.DeleteBrand, name='delete_brand'),

	path('category/', views.ViewCategory, name='view_category'),
	path('category/add/', views.AddCategory, name='add_category'),
	path('category/delete/<int:category_id>', views.DeleteCategory, name='delete_category'),
	path('category/update/<int:category_id>', views.UpdateCategory, name='update_category'),

	path('supplier/', views.ViewSupplier, name='view_supplier'),
	path('supplier/add/', views.AddSupplier, name= 'add_supplier'),
	path('supplier/update/<int:supplier_id>/', views.UpdateSupplier, name='update_supplier'),
	path('supplier/delete/<int:supplier_id>/', views.DeleteSupplier, name='delete_supplier'),


]

LpgErp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inventory.urls')),
    path('', include('accounts.urls')),
    path('', include('mart.urls')),
    path('', include('gross.urls')),
    path('', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

	path('account/register/', views.register_view, name='register'),
	path('', views.login_view, name='login'),
	path('account/logout/', views.logout_view, name='logout'),

	path('account/staff', views.staff_view, name='staff'),
	path('account/reject-staff/<int:staff_id>/', views.delete_staff, name='delete_staff'),
	path('account/update-staff/<int:staff_id>/', views.update_staff, name='update_staff'),

	path('account/admin/', views.AdminView, name='admin'),
	path('account/reject-admin/<int:admin_id>/', views.delete_admin, name='delete_admin'),
	path('account/update-admin/<int:admin_id>/', views.update_admin, name='update_admin'),

	path('account/customer/', views.CustomerView, name='customer'),
	path('account/add-customer/', views.add_customer, name='add_customer'),
	path('account/update-info/<int:customer_id>/', views.update_customer, name='update_customer'),
	path('account/remove-customer/<int:customer_id>/', views.delete_customer, name='delete_customer'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
		
		path('dashboard/account/update', views.UpdateAccountInfo, name='update_account'),
		

]

gross/urls.py
from django.urls import path
from . import views


app_name = 'gross'

urlpatterns = [
		
		path('sale/add/', views.AddSale, name='add_sale'),
		path('sale/view/', views.ViewSale, name='view_sale'),
		path('sale/update/<int:sale_id>/', views.UpdateSale, name='update_sale'),
		path('sale/delete/<int:sale_id>/', views.DeleteSale, name='delete_sale'),

		path('due/view/', views.ViewDue, name='view_due'),
		path('due/add/', views.AddDue, name='add_due'),
		path('due/update/<int:due_id>/', views.UpdateDue, name='update_due'),
		path('due/delete/<int:due_id>/', views.DeleteDue, name='delete_due'),

]

mart/urls.py
from django.urls import path
from . import views

app_name = 'mart'

urlpatterns = [

	path('product/', views.product_view, name='product'),
	path('product/add/', views.add_product, name='add_product'),
	path('product/update/<int:product_id>/', views.update_product, name='update_product'),
	path('product/delete/<int:product_id>/', views.delete_product, name='delete_product'),

	path('add/purchase', views.add_purchase, name='add_purchase'),
	path('purchase/all/', views.view_purchase, name='view_purchase'),
	path('delete/purchase/<int:purchase_id>/', views.delete_purchase, name='delete_purchase'),
	path('update/purchase/<int:purchase_id>/', views.update_purchase, name='update_purchase'),

	path('add/return/', views.add_return, name='add_return'),
	path('return/all/', views.view_return, name='view_return'),
	path('return/update/<int:return_id>/', views.update_return, name='update_return'),
	path('return/delete/<int:return_id>/', views.delete_return, name='delete_return'),

]

Inventory/models.py
from django.db import models

# Create your models here.

class Category(models.Model):

	weight = models.CharField(max_length=100, null=False, blank=False)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.weight)

	class Meta:
		verbose_name_plural='Categories'


class Brand(models.Model):

	name = models.CharField(max_length=200, blank=False, null=False)
	email = models.EmailField(blank=False, null=False)
	phone = models.CharField(max_length=18)
	address = models.CharField(max_length=200, default='Unknown')
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name

class Supplier(models.Model):

	brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
	contact_name = models.CharField(max_length=200)
	address = models.CharField(max_length=200, blank=True, null=True)
	phone = models.CharField(max_length=20)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.contact_name} - {self.brand}'

dashboard/models.py
from django.db import models

# Create your models here.

Inventory/forms.py
from django import forms
from .models import Brand, Category, Supplier

class BrandForm(forms.ModelForm):
    
    class Meta:
        model = Brand
        fields = ['name', 'email', 'phone', 'address']

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['weight']



class SupplierForm(forms.ModelForm):

    class Meta:
        model = Supplier
        fields = ['brand', 'contact_name', 'address', 'phone']

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate
from django.contrib.auth.password_validation import validate_password
from accounts.models import CustomUser

class AccountUpdateForm(forms.ModelForm):
    current_password = forms.CharField(
        label='Current Password',
        widget=forms.PasswordInput,
        required=False,
    )

    new_password = forms.CharField(
        label='New Password',
        widget=forms.PasswordInput,
        required=False,
    )

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'phone_number']

    def clean_new_password(self):
        new_password = self.cleaned_data.get('new_password')
        
        if new_password:
        	validate_password(new_password, self.instance)
        return new_password

    def clean(self):
        cleaned_data = super().clean()
        current_password = cleaned_data.get('current_password')
        user = self.instance

        if current_password and not authenticate(username=user.username, password=current_password):
            raise forms.ValidationError('Invalid current password.')

        return cleaned_data

Inventory/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib import messages
from .models import Brand, Category, Supplier
from .forms import BrandForm, CategoryForm, SupplierForm
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_users
from accounts.models import CustomUser
from mart.models import Product, Return
from gross.models import Sale, Due
from django.views.decorators.cache import cache_page

# Create your views here.
@login_required(login_url='accounts:login')
def DashBoard(request):

    current_user = request.user

    total_staff = CustomUser.objects.filter(role='staff').count()
    total_admin = CustomUser.objects.filter(role='admin').count()
    total_product = Product.objects.all().count()
    total_return = Return.objects.all().count()
    total_sale = Sale.objects.all().count()
    total_due = Due.objects.all().count()

    context = {
        'user':current_user,
        'total_due':total_due,
        'total_sale':total_sale,
        'total_return':total_return,
        'total_product':total_product,
        'total_staff':total_staff,
        'total_admin':total_admin,
    }

    return render(request, 'inventory/dashboard.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def AddBrand(request):
    if request.method == 'POST':
        form = BrandForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Brand added successfully.')
            return redirect('inventory:all_brand') 
    else:
        form = BrandForm()
    return render(request, 'inventory/add_brand.html', {'form': form})

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def UpdateBrand(request, brand_id):

    brand = get_object_or_404(Brand, pk=brand_id)

    if request.method == 'POST':
        form = BrandForm(request.POST, instance=brand)
        if form.is_valid():
            form.save()
            messages.success(request, 'Brand updated successfully.')
            return redirect('inventory:all_brand')
    else:
        form = BrandForm(instance=brand)

    return render(request, 'inventory/update_brand.html', {'form': form, 'brand': brand})




@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def DeleteBrand(request, brand_id):

    brand = get_object_or_404(Brand, pk=brand_id)

    if request.method == 'POST':
        brand.delete()
        messages.warning(request, 'Brand removed successfully.')

    return redirect('inventory:all_brand')


@cache_page(60*15)	
@login_required(login_url='accounts:login')
def AllBrand(request):
	all_brand = Brand.objects.all().order_by('-created_at')
	context = {
		'brands':all_brand,
	}
	return render(request, 'inventory/all_brand.html', context)

@cache_page(60*15)
@login_required(login_url='accounts:login')
def ViewCategory(request):
    categories = Category.objects.all()
    print('DB Called')
    context = {'categories':categories}
    return render(request, 'inventory/category/view_category.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def AddCategory(request):

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category added successfully.')
            return redirect('inventory:view_category')
    else:
        form = CategoryForm()

    return render(request, 'inventory/category/add_category.html')



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def DeleteCategory(request, category_id):

    category = get_object_or_404(Category, pk=category_id)

    if request.method == 'POST':
        category.delete()
        messages.warning(request, 'Category removed successfully.')
    return redirect('inventory:view_category')



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def UpdateCategory(request, category_id):
    category = get_object_or_404(Category, pk=category_id)

    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category updated successfully.')
            return redirect('inventory:view_category')
    else:
        form = CategoryForm(instance=category)

    return render(request, 'inventory/category/add_category.html', {'form': form, 'category': category})




@cache_page(60*15)
@login_required(login_url='accounts:login')
def ViewSupplier(request):
    suppliers = Supplier.objects.all()
    context = {'suppliers':suppliers}
    return render(request, 'inventory/view_supplier.html', context)



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def AddSupplier(request):
    brand = Brand.objects.all()
    if request.method == 'POST':
        form = SupplierForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Supplier added successfully.')
            return redirect('inventory:view_supplier')
    return render(request, 'inventory/add_supplier.html', {'brand':brand})
    
@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def DeleteSupplier(request, supplier_id):
    supplier = get_object_or_404(Supplier, pk=supplier_id)
    if request.method == 'POST':
        supplier.delete()
        messages.warning(request, 'Supplier has been removed.')
    return redirect('inventory:view_supplier')    

def UpdateSupplier(request):
    pass

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, update_session_auth_hash
from .forms import AccountUpdateForm

@login_required
def UpdateAccountInfo(request):
    if request.method == 'POST':
        form = AccountUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)

            current_password = form.cleaned_data.get('current_password')
            if current_password and not authenticate(username=user.username, password=current_password):
                messages.error(request, 'Invalid current password.')
                return redirect('dashboard:update_account')

            new_password = form.cleaned_data.get('new_password')
            if new_password:
                user.set_password(new_password)
                update_session_auth_hash(request, user)

            user.save()
            messages.success(request, 'Your account information was successfully updated.')
            return redirect('inventory:dashboard')
        else:
        	for field, errors in form.errors.items():
        		for error in errors:
        			messages.error(request, error)
    context = {'user':request.user}

    return render(request, 'dashboard/account_update.html', context)

templates/inventory/all_brand.html
{% extends 'base.html' %}
{% block title %} All Brand {% endblock %}
{% block content %}

<div class="page-wrapper">
<div class="container-fluid">
 <div class="card">
    <div class="card-body">
      <h5 class="card-title">All Brands </h5>
      <div class="table-responsive">
        <table
          id="zero_config"
          class="table table-striped table-bordered"
        >
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Address</th>
              <th>Date</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
    		{% for brand in brands %}
            <tr>
              <td>{{brand.name}}</td>
              <td>{{brand.email}}</td>
              <td>{{brand.phone}}</td>
              <td>{{brand.address}}</td>
              <td>{{brand.created_at}}</td>
              <td><a href="{% url 'inventory:update_brand' brand.id %}" class="btn btn-outline-info"><i class="mdi mdi-pencil-box" style="font-size: 20px;"></i></a></td>
              <td>
              <!-- Form for the Delete button -->
              <form id="delete-form-{{ brand.id }}" method="post" action="{% url 'inventory:delete_brand' brand.id %}">
                {% csrf_token %}
                <button type="button" onclick="showDeleteConfirmation({{ brand.id }})" class="btn btn-outline-info">
                  <i class="mdi mdi-delete" style="font-size: 20px;"></i>
                </button>
              </form>
            </td>
            </tr>

   			{% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</div>



{% endblock %}

templates/inventory/dashboard.html
 {% extends 'base.html' %}
 {% load static %}
 {% block title %} Dashboard {% endblock %}
 {% block content %}
 <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">Dashboard</h4>
              <div class="ms-auto text-end">
              </div>
            </div>
          </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
          <!-- ============================================================== -->
          <!-- Sales Cards  -->
          <!-- ============================================================== -->
          <div class="row">
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
               <a href="{% url 'inventory:dashboard' %}">
              <div class="card card-hover">
                <div class="box bg-cyan text-center">
                  <h1 class="font-light text-white">
                   <i class="mdi mdi-view-dashboard"></i>
                  </h1>
                  <h6 class="text-white">Dashboard</h6>
                </div>
              </div>
                </a>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-4 col-xlg-3">
               <a href="{% url 'gross:add_sale' %}">
              <div class="card card-hover">
                <div class="box bg-success text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-chart-areaspline"></i>
                  </h1>
                  <h6 class="text-white">Sale</h6>
                </div>
              </div>
            </a>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
               <a href="{% url 'gross:add_due' %}">
              <div class="card card-hover">
                <div class="box bg-warning text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-collage"></i>
                  </h1>
                  <h6 class="text-white">Due</h6>
                </div>
              </div>
              </a>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
               <a href="{% url 'mart:add_product' %}">
              <div class="card card-hover">
                <div class="box bg-danger text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-border-outside"></i>
                  </h1>
                  <h6 class="text-white">Product</h6>
                </div>
              </div>
            </a>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
              <div class="card card-hover">
                 <a href="{% url 'inventory:add_supplier' %}">
                <div class="box bg-info text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-arrow-all"></i>
                  </h1>
                  <h6 class="text-white">Supplier</h6>
                </div>
              </div>
            </a>
            </div>
            <!-- Column -->
            <!-- Column -->
            <div class="col-md-6 col-lg-4 col-xlg-3">
               <a href="{% url 'accounts:add_customer' %}">
              <div class="card card-hover">
                <div class="box bg-danger text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-receipt"></i>
                  </h1>
                  <h6 class="text-white">Customer</h6>
                </div>
              </div>
            </a>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
               <a href="{% url 'mart:add_return' %}">
              <div class="card card-hover">
                <div class="box bg-info text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-relative-scale"></i>
                  </h1>
                  <h6 class="text-white">Return</h6>
                </div>
              </div>
            </a>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
               <a href="{% url 'inventory:add_category' %}">
              <div class="card card-hover">
                <div class="box bg-cyan text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-pencil"></i>
                  </h1>
                  <h6 class="text-white">Category</h6>
                </div>
              </div>
            </a>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
               <a href="{% url 'inventory:brand' %}">
              <div class="card card-hover">
                <div class="box bg-success text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-calendar-check"></i>
                  </h1>
                  <h6 class="text-white">Brand</h6>
                </div>
              </div>
            </a>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-2 col-xlg-3">
               <a href="{% url 'mart:add_purchase' %}">
              <div class="card card-hover">
                <div class="box bg-warning text-center">
                  <h1 class="font-light text-white">
                    <i class="mdi mdi-alert"></i>
                  </h1>
                  <h6 class="text-white">Purchase</h6>
                </div>
              </div>
            </a>
            </div>
            <!-- Column -->
          </div>
          <!-- ============================================================== -->
          <!-- Sales chart -->
          <!-- ============================================================== -->
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-body">
                  <div class="d-md-flex align-items-center">
                    <div>
                      <h4 class="card-title">Site Analysis</h4>
                      <h5 class="card-subtitle">Overview of Latest Month</h5>
                    </div>
                  </div>
                  <div class="row">
                    <!-- column -->
                    <div class="col-lg-9">
                      <div class="flot-chart">
                        <div
                          class="flot-chart-content"
                          id="flot-line-chart"
                        ></div>
                      </div>
                    </div>
                    <div class="col-lg-3">
                      <div class="row">
                        <div class="col-6">
                          <div class="bg-dark p-10 text-white text-center">
                            <i class="mdi mdi-account fs-3 mb-1 font-16"></i>
                            <h5 class="mb-0 mt-1">{{total_admin}}</h5>
                            <small class="font-light">Total Admin</small>
                          </div>
                        </div>
                        <div class="col-6">
                          <div class="bg-dark p-10 text-white text-center">
                            <i class="mdi mdi-account fs-3 font-16"></i>
                            <h5 class="mb-0 mt-1">{{total_staff}}</h5>
                            <small class="font-light">Total Staff</small>
                          </div>
                        </div>
                        <div class="col-6 mt-3">
                          <div class="bg-dark p-10 text-white text-center">
                            <i class="mdi mdi-cart fs-3 mb-1 font-16"></i>
                            <h5 class="mb-0 mt-1">{{total_product}}</h5>
                            <small class="font-light">Total Product</small>
                          </div>
                        </div>
                        <div class="col-6 mt-3">
                          <div class="bg-dark p-10 text-white text-center">
                            <i class="mdi mdi-tag fs-3 mb-1 font-16"></i>
                            <h5 class="mb-0 mt-1">{{total_sale}}</h5>
                            <small class="font-light">Total Sale</small>
                          </div>
                        </div>
                        <div class="col-6 mt-3">
                          <div class="bg-dark p-10 text-white text-center">
                            <i class="mdi mdi-table fs-3 mb-1 font-16"></i>
                            <h5 class="mb-0 mt-1">{{total_due}}</h5>
                            <small class="font-light">Total Due</small>
                          </div>
                        </div>
                        <div class="col-6 mt-3">
                          <div class="bg-dark p-10 text-white text-center">
                            <i class="mdi mdi-backburger fs-3 mb-1 font-16"></i>
                            <h5 class="mb-0 mt-1">{{total_return}}</h5>
                            <small class="font-light">Total Return</small>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- column -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        {% include 'includes/footer.html' %}
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
      </div> 


{% endblock %}

templates/inventory/view_supplier.html
{% extends 'base.html' %}
{% block title %} All Supplier {% endblock %}
{% block content %}

<div class="page-wrapper">
<div class="container-fluid">
 <div class="card">
    <div class="card-body">
      <h5 class="card-title">All Supplier's </h5>
      <div class="table-responsive">
        <table
          id="zero_config"
          class="table table-striped table-bordered"
        >
          <thead>
            <tr>
              <th>Brand</th>
              <th>Contact Person</th>
              <th>Address</th>
              <th>Brand Location</th>
              <th>Phone</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
    		{% for supplier in suppliers %}
            <tr>
              <td>{{supplier.brand}}</td>
              <td>{{supplier.contact_name}}</td>
              <td>{{supplier.address}}</td>
              <td>{{supplier.brand.address}}</td>
              <td>{{supplier.phone}}</td>
              <td><a href="{% url 'inventory:update_supplier' supplier.id %}" class="btn btn-outline-info"><i class="mdi mdi-pencil-box" style="font-size: 20px;"></i></a></td>
              <td>
              <!-- Form for the Delete button -->
              <form id="delete-form-{{ supplier.id }}" method="post" action="{% url 'inventory:delete_supplier' supplier.id %}">
                {% csrf_token %}
                <button type="button" onclick="showDeleteConfirmation({{ supplier.id }})" class="btn btn-outline-info">
                  <i class="mdi mdi-delete" style="font-size: 20px;"></i>
                </button>
              </form>
            </td>
            </tr>

   			{% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</div>



{% endblock %}