Inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [

	path('dashboard/', views.DashBoard, name='dashboard'),

	path('brand/add/', views.AddBrand, name='brand'),
	path('brand/', views.AllBrand, name='all_brand'),
	path('brand/update/<int:brand_id>/', views.UpdateBrand, name='update_brand'),
	path('brand/delete/<int:brand_id>/', views.DeleteBrand, name='delete_brand'),

	path('category/', views.ViewCategory, name='view_category'),
	path('category/add/', views.AddCategory, name='add_category'),
	path('category/delete/<int:category_id>', views.DeleteCategory, name='delete_category'),
	path('category/update/<int:category_id>', views.UpdateCategory, name='update_category'),

	path('supplier/', views.ViewSupplier, name='view_supplier'),
	path('supplier/add/', views.AddSupplier, name= 'add_supplier'),
	path('supplier/update/<int:supplier_id>/', views.UpdateSupplier, name='update_supplier'),
	path('supplier/delete/<int:supplier_id>/', views.DeleteSupplier, name='delete_supplier'),


]

LpgErp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inventory.urls')),
    path('', include('accounts.urls')),
    path('', include('mart.urls')),
    path('', include('gross.urls')),
    path('', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

	path('account/register/', views.register_view, name='register'),
	path('', views.login_view, name='login'),
	path('account/logout/', views.logout_view, name='logout'),

	path('account/staff', views.staff_view, name='staff'),
	path('account/reject-staff/<int:staff_id>/', views.delete_staff, name='delete_staff'),
	path('account/update-staff/<int:staff_id>/', views.update_staff, name='update_staff'),

	path('account/admin/', views.AdminView, name='admin'),
	path('account/reject-admin/<int:admin_id>/', views.delete_admin, name='delete_admin'),
	path('account/update-admin/<int:admin_id>/', views.update_admin, name='update_admin'),

	path('account/customer/', views.CustomerView, name='customer'),
	path('account/add-customer/', views.add_customer, name='add_customer'),
	path('account/update-info/<int:customer_id>/', views.update_customer, name='update_customer'),
	path('account/remove-customer/<int:customer_id>/', views.delete_customer, name='delete_customer'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
		
		path('dashboard/account/update', views.UpdateAccountInfo, name='update_account'),
		

]

gross/urls.py
from django.urls import path
from . import views


app_name = 'gross'

urlpatterns = [
		
		path('sale/add/', views.AddSale, name='add_sale'),
		path('sale/view/', views.ViewSale, name='view_sale'),
		path('sale/update/<int:sale_id>/', views.UpdateSale, name='update_sale'),
		path('sale/delete/<int:sale_id>/', views.DeleteSale, name='delete_sale'),

		path('due/view/', views.ViewDue, name='view_due'),
		path('due/add/', views.AddDue, name='add_due'),
		path('due/update/<int:due_id>/', views.UpdateDue, name='update_due'),
		path('due/delete/<int:due_id>/', views.DeleteDue, name='delete_due'),

]

mart/urls.py
from django.urls import path
from . import views

app_name = 'mart'

urlpatterns = [

	path('product/', views.product_view, name='product'),
	path('product/add/', views.add_product, name='add_product'),
	path('product/update/<int:product_id>/', views.update_product, name='update_product'),
	path('product/delete/<int:product_id>/', views.delete_product, name='delete_product'),

	path('add/purchase', views.add_purchase, name='add_purchase'),
	path('purchase/all/', views.view_purchase, name='view_purchase'),
	path('delete/purchase/<int:purchase_id>/', views.delete_purchase, name='delete_purchase'),
	path('update/purchase/<int:purchase_id>/', views.update_purchase, name='update_purchase'),

	path('add/return/', views.add_return, name='add_return'),
	path('return/all/', views.view_return, name='view_return'),
	path('return/update/<int:return_id>/', views.update_return, name='update_return'),
	path('return/delete/<int:return_id>/', views.delete_return, name='delete_return'),

]

templates/includes/footer.html
<footer class="footer text-center">
          All Rights Reserved by NOOB Designed and Developed by
          <a href="https://github.com/ripnoob">ripnoob</a>.
        </footer>

templates/includes/messages.html
{% for msg in messages %}
    <center>
    <div class="alert alert-success alert-dismissible fade show" role='alert'>
        <strong>Hey!</strong> {{msg}}
        <button type="button" class="btn-close" data-bs-dismiss='alert' aria-label='class'></button>
    </div>
    </center>
{% endfor %}

templates/includes/nav.html
 <aside class="left-sidebar" data-sidebarbg="skin5">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
          <!-- Sidebar navigation-->
          <nav class="sidebar-nav">
            <ul id="sidebarnav" class="pt-4">
              <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="{% url 'inventory:dashboard' %}"
                  aria-expanded="false"
                  ><i class="mdi mdi-view-dashboard"></i
                  ><span class="hide-menu">Dashboard</span></a
                >
              </li>
            
              </li>
                <li class="sidebar-item">
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-tag-multiple"></i
                  ><span class="hide-menu">Brand's</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'inventory:brand' %}" class="sidebar-link"
                      ><i class="mdi mdi-note-plus"></i
                      ><span class="hide-menu"> Add Brand </span></a
                    >
                  </li>
                  <li class="sidebar-item">
                    <a href="{% url 'inventory:all_brand' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View / Manage </span></a
                    >
                  </li>
                </ul>
              </li>

              <li class="sidebar-item">
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-animation"></i
                  ><span class="hide-menu">Categories</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'inventory:add_category' %}" class="sidebar-link"
                      ><i class="mdi mdi-note-plus"></i
                      ><span class="hide-menu"> Add Category </span></a
                    >
                  </li>
                  <li class="sidebar-item">
                    <a href="{% url 'inventory:view_category' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View / Manage </span></a
                    >
                  </li>
                </ul>
              </li>

              <li class="sidebar-item">
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-gas-cylinder"></i
                  ><span class="hide-menu">Product's</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'mart:add_product' %}" class="sidebar-link"
                      ><i class="mdi mdi-note-plus"></i
                      ><span class="hide-menu"> Add Product </span></a
                    >
                  </li>
                  <li class="sidebar-item">
                    <a href="{% url 'mart:product' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View / Manage </span></a
                    >
                  </li>

                </ul>
              </li>
              
               <li class="sidebar-item">
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-truck-delivery"></i
                  ><span class="hide-menu">Suppliers</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'inventory:add_supplier' %}" class="sidebar-link"
                      ><i class="mdi mdi-note-plus"></i
                      ><span class="hide-menu"> Add Supplier </span></a
                    >
                  </li>
                  <li class="sidebar-item">
                    <a href="{% url 'inventory:view_supplier' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View / Manage </span></a
                    >
                  </li>
                  <li class="sidebar-item">
                    <a href="form-basic.html" class="sidebar-link"
                      ><i class="mdi mdi-note-plus"></i
                      ><span class="hide-menu"> Add Company Payment </span></a
                    >
                  </li>
                  <li class="sidebar-item">
                    <a href="form-wizard.html" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View / Manage Payment </span></a
                    >
                  </li>
                </ul>
              </li>
              
               <li class="sidebar-item">
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-account-circle"></i
                  ><span class="hide-menu">Customers</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'accounts:add_customer' %}" class="sidebar-link"
                      ><i class="mdi mdi-account-plus"></i
                      ><span class="hide-menu"> Add Customer </span></a
                    >
                  </li>

                  <li class="sidebar-item">
                    <a href="{% url 'accounts:customer' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View / Manage </span></a
                    >
                  </li>

                </ul>
              </li>

              <li class="sidebar-item">
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-account-circle"></i
                  ><span class="hide-menu">Account Management</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'accounts:staff' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View / Manage Staff </span></a
                    >
                  </li>

                  <li class="sidebar-item">
                    <a href="{% url 'accounts:admin' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View / Manage Admin </span></a
                    >
                  </li>

                </ul>
              </li>
            
               <li class="sidebar-item">    
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-cart-plus"></i
                  ><span class="hide-menu">Purchase</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">

                  <li class="sidebar-item">
                    <a href="{% url 'mart:add_purchase' %}" class="sidebar-link"
                      ><i class="mdi mdi-note-plus"></i
                      ><span class="hide-menu"> Purchases </span></a
                    >
                  </li>


                  <li class="sidebar-item">
                    <a href="{% url 'mart:view_purchase' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> Purchase History </span></a
                    >
                  </li>

                </ul>
              </li>

               <li class="sidebar-item">    
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-backburger"></i>
                  <span class="hide-menu">Return</span></a>
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'mart:add_return' %}" class="sidebar-link"
                      ><i class="mdi mdi-note-plus"></i
                      ><span class="hide-menu"> Create return voucher </span></a
                    >
                  </li>
                  <li class="sidebar-item">
                    <a href="{% url 'mart:view_return' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> View all </span></a
                    >
                  </li>

                </ul>
              </li>

                <li class="sidebar-item">
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-cart-outline"></i
                  ><span class="hide-menu">Sale</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'gross:add_sale' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> Add Sale </span></a
                    >
                  </li>

        
                  <li class="sidebar-item">
                    <a href="{% url 'gross:view_sale' %}" class="sidebar-link"
                      ><i class="mdi mdi-view-list"></i
                      ><span class="hide-menu"> Sale Record's </span></a
                    >
                  </li>

                </ul>
              </li>
              
              <li class="sidebar-item">
                <a
                  class="sidebar-link has-arrow waves-effect waves-dark"
                  href="javascript:void(0)"
                  aria-expanded="false"
                  ><i class="mdi mdi-clipboard-flow"></i
                  ><span class="hide-menu">Due List</span></a
                >
                <ul aria-expanded="false" class="collapse first-level">
                  <li class="sidebar-item">
                    <a href="{% url 'gross:add_due' %}" class="sidebar-link"
                      ><i class="mdi mdi-note-plus"></i
                      ><span class="hide-menu"> Create Due </span></a
                    >
                  </li>

                  <li class="sidebar-item">
                    <a href="{% url 'gross:view_due' %}" class="sidebar-link"
                      ><i class="{% url 'gross:view_due' %}"></i
                      ><span class="hide-menu"> Due Record's</span></a
                    >
                  </li>

                </ul>
              </li>

            </ul>
          </nav>
          <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
      </aside>

templates/includes/top.html
{% load static %}
<header class="topbar" data-navbarbg="skin5">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
          <div class="navbar-header" data-logobg="skin5">
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="{% url 'inventory:dashboard' %}">
              <!-- Logo icon -->
              <b class="logo-icon ps-2">
                <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                <!-- Dark Logo icon -->
                <img
                  src="{% static '/assets/images/logo-icon.png' %}"
                  alt="homepage"
                  class="light-logo"
                  width="25"
                />
              </b>
              <!--End Logo icon -->
              <!-- Logo text -->
              <span class="logo-text ms-2">
                <!-- dark Logo text -->
                <img
                  src="{% static '/assets/images/logo-text.png' %}"
                  alt="homepage"
                  class="light-logo"
                />
              </span>
              <!-- Logo icon -->
              <!-- <b class="logo-icon"> -->
              <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
              <!-- Dark Logo icon -->
              <!-- <img src="../assets/images/logo-text.png" alt="homepage" class="light-logo" /> -->

              <!-- </b> -->
              <!--End Logo icon -->
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a
              class="nav-toggler waves-effect waves-light d-block d-md-none"
              href="javascript:void(0)"
              ><i class="ti-menu ti-close"></i
            ></a>
          </div>
          <!-- ============================================================== -->
          <!-- End Logo -->
          <!-- ============================================================== -->
          <div
            class="navbar-collapse collapse"
            id="navbarSupportedContent"
            data-navbarbg="skin5"
          >
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-start me-auto">
              <li class="nav-item d-none d-lg-block">
                <a
                  class="nav-link sidebartoggler waves-effect waves-light"
                  href="javascript:void(0)"
                  data-sidebartype="mini-sidebar"
                  ><i class="mdi mdi-menu font-24"></i
                ></a>
              </li>
              <!-- ============================================================== -->
              <!-- create new -->
              <!-- ============================================================== -->
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <span class="d-none d-md-block"
                    >Create New <i class="fa fa-angle-down"></i
                  ></span>
                  <span class="d-block d-md-none"
                    ><i class="fa fa-plus"></i
                  ></span>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Product's</a></li>
                  <li><a class="dropdown-item" href="#">Sales</a></li>
                  <li><hr class="dropdown-divider" /></li>
                  <li>
                    {% if request.user.role == 'admin' %}
                    <li><a class="dropdown-item" href="{% url 'inventory:brand' %}">Brand</a></li>
                    <li><a class="dropdown-item" href="{% url 'inventory:add_category' %}">Category</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Account</a></li>
                  {% endif %}
                  </li>
                </ul>
              </li>
              <!-- ============================================================== -->
              <!-- Search -->
              <!-- ============================================================== -->
              <li class="nav-item search-box">
                <a
                  class="nav-link waves-effect waves-dark"
                  href="javascript:void(0)"
                  ><i class="mdi mdi-magnify fs-4"></i
                ></a>
                <form class="app-search position-absolute">
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Search &amp; enter"
                  />
                  <a class="srh-btn"><i class="mdi mdi-window-close"></i></a>
                </form>
              </li>
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-end">
              <!-- ============================================================== -->
              <li class="nav-item dropdown">
                <a
                  class="
                    nav-link
                    dropdown-toggle
                    text-muted
                    waves-effect waves-dark
                    pro-pic
                  "
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <img
                    src="{% static '/assets/images/users/1.jpg' %}"
                    alt="user"
                    class="rounded-circle"
                    width="31"
                  />
                </a>

                <ul
                  class="dropdown-menu dropdown-menu-end user-dd animated"
                  aria-labelledby="navbarDropdown"
                >
                  <a class="dropdown-item" href="javascript:void(0)"
                    ><i class="mdi mdi-account me-1 ms-1"></i> {{user.username}}</a
                  >
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'dashboard:update_account'%}"
                    ><i class="mdi mdi-settings me-1 ms-1"></i> Account
                    Setting</a
                  >
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'accounts:logout' %}"
                    ><i class="fa fa-power-off me-1 ms-1"></i> Logout</a
                  >
                  <div class="dropdown-divider"></div>
                </ul>
              </li>
              <!-- ============================================================== -->
              <!-- User profile and search -->
              <!-- ============================================================== -->
            </ul>
          </div>
        </nav>
      </header>