LpgErp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inventory.urls')),
    path('', include('accounts.urls')),
    path('', include('mart.urls')),
    path('', include('gross.urls')),
    path('', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gross/urls.py
from django.urls import path
from . import views


app_name = 'gross'

urlpatterns = [
		
		path('sale/add/', views.AddSale, name='add_sale'),
		path('sale/view/', views.ViewSale, name='view_sale'),
		path('sale/update/<int:sale_id>/', views.UpdateSale, name='update_sale'),
		path('sale/delete/<int:sale_id>/', views.DeleteSale, name='delete_sale'),

		path('due/view/', views.ViewDue, name='view_due'),
		path('due/add/', views.AddDue, name='add_due'),
		path('due/update/<int:due_id>/', views.UpdateDue, name='update_due'),
		path('due/delete/<int:due_id>/', views.DeleteDue, name='delete_due'),

]

mart/urls.py
from django.urls import path
from . import views

app_name = 'mart'

urlpatterns = [

	path('product/', views.product_view, name='product'),
	path('product/add/', views.add_product, name='add_product'),
	path('product/update/<int:product_id>/', views.update_product, name='update_product'),
	path('product/delete/<int:product_id>/', views.delete_product, name='delete_product'),

	path('add/purchase', views.add_purchase, name='add_purchase'),
	path('purchase/all/', views.view_purchase, name='view_purchase'),
	path('delete/purchase/<int:purchase_id>/', views.delete_purchase, name='delete_purchase'),
	path('update/purchase/<int:purchase_id>/', views.update_purchase, name='update_purchase'),

	path('add/return/', views.add_return, name='add_return'),
	path('return/all/', views.view_return, name='view_return'),
	path('return/update/<int:return_id>/', views.update_return, name='update_return'),
	path('return/delete/<int:return_id>/', views.delete_return, name='delete_return'),

]

gross/models.py
from django.db import models
from mart.models import Product
from accounts.models import Customer

# Create your models here.

class Sale(models.Model):
	
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	prod_price = models.FloatField()	
	extra_cost = models.FloatField(blank=True, null=True)
	paid = models.FloatField()
	quantity = models.IntegerField()
	is_refill = models.BooleanField()
	is_wholesale = models.BooleanField()
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.product} - {self.customer.get_full_name()}'

	def total_cost(self):
		return (self.prod_price * self.quantity) + self.extra_cost



class Due(models.Model):

	sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
	due_amount = models.FloatField()
	is_paid = models.BooleanField(default=False)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.sale.customer.get_full_name} - {self.product} - {self.due_amount}'

gross/forms.py
from django import forms
from .models import Sale, Due

class SaleForm(forms.ModelForm):
	
	class Meta:
		model = Sale
		fields = ['product', 'customer', 'prod_price', 'extra_cost', 'paid', 'quantity', 'is_refill', 'is_wholesale']

		extra_cost = forms.FloatField(initial=0.0)


class DueForm(forms.ModelForm):

	class Meta:
		model = Due
		fields = ['sale', 'due_amount', 'is_paid']


class DueStatusForm(forms.ModelForm):

	class Meta:
		model = Due
		fields = ['is_paid']
		widgets = {
		'is_paid': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

gross/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Sale, Due
from mart.models import Product
from accounts.models import Customer
from .forms import SaleForm, DueForm, DueStatusForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_users
from django.views.decorators.cache import cache_page

# Create your views here.
login_required(login_url='accounts:login') 
def AddSale(request):
	products = Product.objects.all()
	customers = Customer.objects.all()

	if request.method == 'POST':
		form = SaleForm(request.POST)
		if form.is_valid():
			sale = form.save()
			messages.success(request, 'Sale record added.')

			paid = form.cleaned_data['paid']
			price = form.cleaned_data['prod_price']
			extra_cost = form.cleaned_data['extra_cost']
			quantity = form.cleaned_data['quantity']
			
			total = (price * quantity) + extra_cost

			if paid < total:
				due = Due.objects.create(
					sale = sale,
					due_amount = total - paid,
					is_paid = False 
					)
				messages.success(request, 'A sale and due record has been added.')


			return redirect('gross:view_sale')
		else:
			for field, errors in form.errors.items():
				for error in errors:
					messages.error(request, error)
					
	context = {'products':products, 'customers':customers}
	return render(request, 'gross/add_sale.html', context)

@cache_page(60*15)
@login_required(login_url='accounts:login')
def ViewSale(request):
	sale_record = Sale.objects.all()
	context = {'sale_record':sale_record}
	return render(request, 'gross/view_sale.html', context) 

def UpdateSale(request, sale_id):
	pass

login_required(login_url='accounts:login')
allowed_users(allowed_roles=['admin'])
def DeleteSale(request, sale_id):
	sale = get_object_or_404(Sale, pk=sale_id)
	if request.method == 'POST':
		sale.delete()
		messages.warning(request, 'Sale record has been deleted.')
	return redirect('gross:view_sale')


@cache_page(60*15)
@login_required(login_url='accounts:login')
def ViewDue(request):

	due = Due.objects.all()
	context = {'due_records':due}
	return render(request, 'gross/view_due.html', context)



login_required(login_url='accounts:login')
def AddDue(request):

	sale = Sale.objects.all()
	if request.method == 'POST':
		form = DueForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Due record has been added.')
			return redirect('gross:view_due')
		else:
			for field, errors in form.errors.items():
				for error in errors:
					messages.error(request, error)
	context = {'sales':sale}
	return render(request, 'gross/add_due.html', context)



login_required(login_url='accounts:login')
def UpdateDue(request, due_id):
    due = get_object_or_404(Due, id=due_id)

    if request.method == 'POST':
        form = DueStatusForm(request.POST, instance=due)
        if form.is_valid():
            is_paid = form.cleaned_data['is_paid']

            due.is_paid = is_paid
            due.save()

            if is_paid:
                sale = due.sale
                sale.paid += due.due_amount 
                sale.save()
                messages.success(request, 'Marked as paid and Sale updated.')
    else:
        form = DueStatusForm(instance=due)

    return redirect('gross:view_due')



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def DeleteDue(request, due_id):
	due = get_object_or_404(Due, pk=due_id)
	if request.method == 'POST':
		due.delete()
		messages.warning(request, 'Due record deleted.')
	return redirect('gross:view_due')
	

templates/gross/add_due.html
{% extends 'base.html' %}
{% block title %} {% if due %}Update Due{% else %}New Due{% endif %} {% endblock %}
{% block content %}

<div class="page-wrapper">
  <div class="container-fluid">
    <div class="row">

  
       <div class="card">
                <form class="form-horizontal" method="POST" {% if due %} action="{% url 'gross:update_due' due_id=due.id %}" 
                {% else %} action="{% url 'gross:add_due'  %}" {% endif %}
                >
                  {% csrf_token %}
                  <div class="card-body">
                    <h4 class="card-title">Due Record</h4>

                  <div class="form-group row">  
                    <label for='role' class="col-sm-3 text-end control-label col-form-label" >Sale</label>    
                    <div class="col-sm-9">
                      <select
                        class="select2 form-select shadow-none"
                        style="width: 100%; height: 36px"
                        aria-label="sale"
                        name="sale"
                    
                      >
                        {% for sale in sales %}
                        <option value="{{sale.id}}" {% if sale == sale %} selected {% endif %} >{{sale}}</option>
                        {% endfor %}
                      </select>
                      </div>
                    </div>


                
                    <div class="form-group row">
                      <label
                        for="price"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Due Amount</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='due_amount'
                          id="due_amount"
                          placeholder="Due Amount"
                          {% if due %} value='{{due.due_amount}}' {% endif %}
                        />
                      </div>
                    </div>


                    <div class="form-group row">
                    <label for="refill" class="col-sm-3 text-end control-label col-form-label">Is Paid</label>
                    <div class="col-sm-9" style="margin-top: 6px;">

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="is_paid_yes" name="is_paid" value="True" required>
                        <label class="form-check-label mb-0" for="is_paid">Yes</label>
                      </div>

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="is_paid" name="is_paid" value="False" required>
                        <label class="form-check-label mb-0" for="is_paid_no">No</label>
                      </div>

                    </div>
                  </div>





                  <div class="border-top">
                    <div class="card-body">
                      <button type="submit" class="btn btn-primary">
                        {% if due %} Update {% else %} Add {% endif %} Record
                      </button>
                    </div>
                  </div>
                </form>


    </div>
  </div>
</div>




{% endblock %}

templates/gross/add_sale.html
{% extends 'base.html' %}
{% block title %} {% if Sale %}Update Sale{% else %}New Sale{% endif %} {% endblock %}
{% block content %}

<div class="page-wrapper">
  <div class="container-fluid">
    <div class="row">

  
       <div class="card">
                <form class="form-horizontal" method="POST" {% if sale %} action="{% url 'gross:update_sale' sale_id=sale.id %}" 
                {% else %} action="{% url 'gross:add_sale'  %}" {% endif %}
                >
                  {% csrf_token %}
                  <div class="card-body">
                    <h4 class="card-title">Sale Record</h4>

                  <div class="form-group row">  
                    <label for='role' class="col-sm-3 text-end control-label col-form-label" >Product</label>    
                    <div class="col-sm-9">
                      <select
                        class="select2 form-select shadow-none"
                        style="width: 100%; height: 36px"
                        aria-label="product"
                        name="product"
                    
                      >
                        {% for product in products %}
                        <option value="{{product.id}}" {% if product == sale_product %} selected {% endif %} >{{product}} - {{product.price}} BDT - {{product.brand}}</option>
                        {% endfor %}
                      </select>
                      </div>
                    </div>



                    <div class="form-group row">  
                    <label for='role' class="col-sm-3 text-end control-label col-form-label" >Customer</label>    
                    <div class="col-sm-9">
                      <select
                        class="select2 form-select shadow-none"
                        style="width: 100%; height: 36px"
                        aria-label="customer"
                        name="customer"
                    
                      >
                        {% for customer in customers %}
                        <option value="{{customer.id}}" {% if customer == sale_customer %} selected {% endif %} >{{customer.get_full_name}} - {{customer.address}}</option>
                        {% endfor %}
                      </select>
                      </div>
                    </div>


                
                    <div class="form-group row">
                      <label
                        for="price"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Price</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='prod_price'
                          id="prod_price"
                          placeholder="Product Price Here"
                          {% if product %} value='{{sale.prod_price}}' {% endif %}
                        />
                      </div>
                    </div>


                      <div class="form-group row">
                      <label
                        for="extra_cost"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Extra Cost</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='extra_cost'
                          id="extra_cost"
                          placeholder="Extra Cost Here"
                          {% if sale %} value='{{sale.extra_cost}}' {% endif %}
                        />
                      </div>
                    </div>

                    <div class="form-group row">
                      <label
                        for="paid"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Paid</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='paid'
                          id="paid"
                          placeholder="Paid Amount Here"
                          {% if product %} value='{{sale.paid}}' {% endif %}
                        />
                      </div>
                    </div>

                    <div class="form-group row">
                      <label
                        for="quantity"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Quantity</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='quantity'
                          id="quantity"
                          placeholder="Product Quantity Here"
                          {% if product %} value='{{sale.quantity}}' {% endif %}
                        />
                      </div>
                    </div>


                   <div class="form-group row">
                    <label for="refill" class="col-sm-3 text-end control-label col-form-label">Is Refill / Warrenty</label>
                    <div class="col-sm-9" style="margin-top: 6px;">

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="is_refill_yes" name="is_refill" value="True" required>
                        <label class="form-check-label mb-0" for="is_refill">Yes</label>
                      </div>

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="is_refill" name="is_refill" value="False" required>
                        <label class="form-check-label mb-0" for="is_refill_no">No</label>
                      </div>

                    </div>
                  </div>


                    <div class="form-group row">
                    <label for="refill" class="col-sm-3 text-end control-label col-form-label">Is wholesale</label>
                    <div class="col-sm-9" style="margin-top: 6px;">

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="is_wholesale_yes" name="is_wholesale" value="True" required>
                        <label class="form-check-label mb-0" for="is_wholesale">Yes</label>
                      </div>

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="is_wholesale" name="is_wholesale" value="False" required>
                        <label class="form-check-label mb-0" for="is_wholesale_no">No</label>
                      </div>

                    </div>
                  </div>





                  <div class="border-top">
                    <div class="card-body">
                      <button type="submit" class="btn btn-primary">
                        {% if sale %} Update {% else %} Add {% endif %} Record
                      </button>
                    </div>
                  </div>
                </form>


    </div>
  </div>
</div>




{% endblock %}

templates/gross/view_due.html
{% extends 'base.html' %}
{% block title %} View Due {% endblock %}
{% block content %}

<div class="page-wrapper">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Records</h5>
                <div class="table-responsive">
                    <table id="zero_config" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Status</th>
                                <th>Due Amount</th>
                                <th>Product Title</th>
                                <th>Customer Name</th>
                                <th>Customer Phone</th>
                                <th>Total Cost</th>
                                <th>Total Paid</th>
                                <th>Date</th>
                                <th class="col-md-1">Update Status</th>
                                <th class="col-md-1">Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for due in due_records %}
                            <tr>
                                <td
                                    {% if due.is_paid %}
                                    style="color: green;"
                                    {% else %}
                                    style="color: red;"
                                    {% endif %}
                                >
                                    {% if due.is_paid %} Paid {% else %} Unpaid {% endif %}
                                </td>
                                <td>{{ due.due_amount }}</td>
                                <td>{{ due.sale.product }}</td>
                                <td>{{ due.sale.customer.get_full_name }}</td>
                                <td>{{ due.sale.customer.phone }}</td>
                                <td>{{ due.sale.total_cost }}</td>
                                <td>{{ due.sale.paid }}</td>
                                <td>{{ due.created_at|date:"M. j, Y" }}</td>
                                <td>
                                   <form method="post" action="{% url 'gross:update_due' due.id %}">
                                        {% csrf_token %}
                                        <div class="d-flex align-items-center">
                                            <div class="form-check">
                                                <input type="checkbox" class="form-check-input" id="is_paid_{{ due.id }}" name="is_paid" {% if due.is_paid %}checked{% endif %}>
                                                <label class="form-check-label" for="is_paid_{{ due.id }}">Paid</label>
                                            </div>
                                            <button type="submit" class="btn btn-outline-info btn-sm ml-2" style="margin: 10px; margin-bottom: 19px;">Update</button>
                                        </div>
                                    </form>
                                </td>
                                <td>
                                    <!-- Form for the Delete button -->
                                    <form id="delete-form-{{ due.id }}" method="post" action="{% url 'gross:delete_due' due.id %}">
                                        {% csrf_token %}
                                        <button type="button" onclick="showDeleteConfirmation({{ due.id }})" class="btn btn-outline-info">
                                            <i class="mdi mdi-delete" style="font-size: 20px;"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/gross/view_sale.html
{% extends 'base.html' %}
{% block title %} View Sale {% endblock %}
{% block content %}

<div class="page-wrapper">
<div class="container-fluid">
 <div class="card">
    <div class="card-body">
      <h5 class="card-title">Records </h5>
      <div class="table-responsive">
        <table
          id="zero_config"
          class="table table-striped table-bordered"
        >
          <thead>
            <tr>
              <th class="col-md-2">Product Title</th>
              <th>Customer Name</th>
              <th>Customer Address</th>
              <th>Selling Price</th>
              <th>Extra Cost</th>
              <th>Total Cost</th>
              <th>Paid</th>
              <th>Refill / Warrenty</th>
              <th>Quantity</th>
              <th>Wholesale</th>
              <th>Sale Date</th>
              <th class="col-md-1">Update</th>
              <th class="col-md-1">Delete</th>
            </tr>
          </thead>
          <tbody>
        {% for sale in sale_record %}
            <tr>
              <td>{{sale.product}}</td>
              <td>{{sale.customer.get_full_name}}</td>
              <td>{{sale.customer.address}}</td>
              <td>{{sale.prod_price}}</td>
              <td>{{sale.extra_cost}}</td>
              <td>{{sale.total_cost}}</td>
              <td>{{sale.paid}}</td>
              <td>{% if sale.is_refill %} Yes {% else %} No {% endif %}</td>
              <td>{{ sale.quantity }}</td>
              <td>{% if sale.is_wholesale %} Yes {% else %} No {% endif %}</td>
              <td>{{sale.created_at|date:"M. j, Y"}}</td>
              <td ><a href="{% url 'gross:update_sale' sale.id %}" class="btn btn-outline-info"><i class="mdi mdi-pencil-box" style="font-size: 20px;"></i></a></td>
              <td>
              <!-- Form for the Delete button -->
              <form id="delete-form-{{ sale.id }}" method="post" action="{% url 'gross:delete_sale' sale.id %}">
                {% csrf_token %}
                <button type="button" onclick="showDeleteConfirmation({{ sale.id }})" class="btn btn-outline-info">
                  <i class="mdi mdi-delete" style="font-size: 20px;"></i>
                </button>
              </form>
            </td>
            </tr>
        {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</div>



{% endblock %}