LpgErp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inventory.urls')),
    path('', include('accounts.urls')),
    path('', include('mart.urls')),
    path('', include('gross.urls')),
    path('', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mart/urls.py
from django.urls import path
from . import views

app_name = 'mart'

urlpatterns = [

	path('product/', views.product_view, name='product'),
	path('product/add/', views.add_product, name='add_product'),
	path('product/update/<int:product_id>/', views.update_product, name='update_product'),
	path('product/delete/<int:product_id>/', views.delete_product, name='delete_product'),

	path('add/purchase', views.add_purchase, name='add_purchase'),
	path('purchase/all/', views.view_purchase, name='view_purchase'),
	path('delete/purchase/<int:purchase_id>/', views.delete_purchase, name='delete_purchase'),
	path('update/purchase/<int:purchase_id>/', views.update_purchase, name='update_purchase'),

	path('add/return/', views.add_return, name='add_return'),
	path('return/all/', views.view_return, name='view_return'),
	path('return/update/<int:return_id>/', views.update_return, name='update_return'),
	path('return/delete/<int:return_id>/', views.delete_return, name='delete_return'),

]

mart/models.py
from django.db import models
from accounts.models import CustomUser
from Inventory.models import Brand, Category, Supplier
# Create your models here.

class Product(models.Model):

	brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	price = models.FloatField()
	quantity = models.IntegerField()
	is_refill = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title
	
	def wholesale_price(self):
		pass


class Purchase(models.Model):

	product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
	supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, blank=True, null=True)
	quantity = models.IntegerField()
	cost = models.FloatField()
	extra_cost = models.FloatField(blank=True, null=True)
	is_refill = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.product} {self.cost}'

	def single_prod_price(self):
		if self.cost and self.extra_cost:
			return (self.cost + self.extra_cost) / float(self.quantity)
		else:
			return 'N/A'
	def total_cost(self):
		return self.cost + self.extra_cost

	



class EmptySylinder(models.Model):
	
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
	brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True)
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
	quantity = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.product




class Return(models.Model):
	
	purchase = models.ForeignKey(Purchase, on_delete=models.SET_NULL, blank=True, null=True)
	quantity = models.IntegerField()
	return_cost = models.FloatField()
	issue = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.purchase.product + '' + quantity

	def returned_product_price(self):
		if self.purchase and self.purchase.single_prod_price():
			return self.purchase.single_prod_price() * float(self.quantity)
		else:
			return 'N/A'
	
	def total_return_cost(self):
		if self.purchase and self.purchase.single_prod_price():
			product_price = self.purchase.single_prod_price() * float(self.quantity)
			return float(product_price) + self.return_cost
		else:
			return 'N/A'

mart/forms.py
from django import forms
from .models import Product, Purchase, Return

class AddProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = ['title', 'category', 'brand', 'price', 'quantity', 'is_refill']



class AddPurchaseForm(forms.ModelForm):
	class Meta:
		model = Purchase
		fields = ['product', 'supplier', 'quantity', 'cost', 'extra_cost', 'is_refill']


class AddReturnVoucher(forms.ModelForm):
	class Meta:
		model = Return
		fields = ['purchase', 'quantity', 'return_cost', 'issue']
				

mart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Purchase, Return
from accounts.decorators import allowed_users
from Inventory.models import Brand, Category, Supplier
from .forms import AddProductForm, AddPurchaseForm, AddReturnVoucher
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_users
from django.views.decorators.cache import cache_page

# Create your views here.

@cache_page(60*15)
def product_view(request):
	product = Product.objects.all().order_by('-created_at')
	print('DB Called.....')
	context = {'products':product}
	return render(request, 'mart/product.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def add_product(request):

    brand = Brand.objects.all()
    category = Category.objects.all()

    if request.method == 'POST':
        form = AddProductForm(request.POST)
        if form.is_valid():
            if not Product.objects.filter(title=form.cleaned_data['title']).exists():
                form.save()
                return redirect('mart:product')
            else:
                messages.error(request, 'Product with this title already exists.')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, error)

    context = {'brand': brand, 'category': category}
    return render(request, 'mart/update_product.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def update_product(request, product_id):
	product = get_object_or_404(Product, pk=product_id)
	brand = Brand.objects.all()
	category = Category.objects.all()
	prod_cat = get_object_or_404(Category, pk=product.category.id)
	prod_brand = get_object_or_404(Brand, pk=product.brand.id)

	if request.method == 'POST':
		form = AddProductForm(request.POST, instance=product)
		if form.is_valid():
			form.save()
			messages.success(request, 'Product updated successfully.')
			return redirect('mart:product')
		else:
			for field, errors in form.errors.items():
				for error in errors:
					messages.error(request, error)
	context = {'brand':brand, 'category':category, 'product':product, 'prod_cat': prod_cat, 'prod_brand':prod_brand }
	return render(request, 'mart/update_product.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def delete_product(request, product_id):
	product = get_object_or_404(Product, pk=product_id)
	if request.method == 'POST':
		product.delete()

	messages.warning(request, f'{product.title} has been removed.')
	return redirect('mart:product')


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def add_purchase(request):
	
	product = Product.objects.all()
	supplier = Supplier.objects.all()
	
	if request.method == 'POST':
		form = AddPurchaseForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Purchase record successfully added.')
			return redirect('mart:view_purchase')
		else:
			for field, errors in form.errors.items():
				for error in errors:
					messages.error(request, error)

	context = {'product':product, 'supplier':supplier}
	return render(request, 'mart/purchase.html', context)

	
@cache_page(60*15)
@login_required(login_url='accounts:login')	
def view_purchase(request):
	purchases = Purchase.objects.all()
	context = {'purchases':purchases}
	return render(request, 'mart/purchase_record.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def delete_purchase(request, purchase_id):
	purchase = get_object_or_404(Purchase, pk=purchase_id)
	if request.method == 'POST':
		purchase.delete()
		messages.warning(request, 'Purchase record has been removed successfully.')
	return redirect('mart:view_purchase')

def update_purchase(request):
	pass

@cache_page(60*15)
@login_required(login_url='accounts:login')
def view_return(request):
	return_voucher = Return.objects.all()
	context = {'return_voucher':return_voucher }
	return render(request, 'mart/views_return.html', context)



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def add_return(request):
	purchase = Purchase.objects.all()
	if request.method == 'POST':
		form = AddReturnVoucher(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Return voucher added.')
			return redirect('mart:view_return')
		else:
			for field, errors in form.errors.items():
				for error in errors:
					messages.error(request, 'error')
	context = {'purchase': purchase}
	return render(request, 'mart/return.html', context)



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def update_return(request, return_id):
	pass



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def delete_return(request, return_id):
	return_record = get_object_or_404(Return, pk=return_id)
	if request.method == 'POST':
		return_record.delete()
		messages.warning(request, 'A return record has been removed.')
	return redirect('mart:view_return')

templates/mart/product.html
{% extends 'base.html' %}
{% block title %} Product List {% endblock %}
{% block content %}

<div class="page-wrapper">
<div class="container-fluid">
 <div class="card">
    <div class="card-body">
      <h5 class="card-title">Product Menu </h5>
      <div class="table-responsive">
        <table
          id="zero_config"
          class="table table-striped table-bordered"
        >
          <thead>
            <tr>
              <th>Title</th>
              <th>Category</th>
              <th>Refill / Warrenty </th>
              <th>Brand</th>
              <th>Price</th>
              <th>Quantity</th>
              <th class="col-md-1">Update</th>
              <th class="col-md-1">Delete</th>
            </tr>
          </thead>
          <tbody>
        {% for product in products %}
            <tr>
              <td>{{product.title}}</td>
              <td>{{product.category}}</td>
              <td>{% if product.is_refill %} Yes {% else %} No {% endif %}</td>
              <td>{{product.brand}}</td>
              <td>{{product.price}}</td>
              <td>{{ product.quantity }}</td>
              <td><a href="{% url 'mart:update_product' product.id %}" class="btn btn-outline-info"><i class="mdi mdi-pencil-box" style="font-size: 20px;"></i></a></td>
              <td>
              <!-- Form for the Delete button -->
              <form id="delete-form-{{ product.id }}" method="post" action="{% url 'mart:delete_product' product.id %}">
                {% csrf_token %}
                <button type="button" onclick="showDeleteConfirmation({{ product.id }})" class="btn btn-outline-info">
                  <i class="mdi mdi-delete" style="font-size: 20px;"></i>
                </button>
              </form>
            </td>
            </tr>
        {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</div>



{% endblock %}

templates/mart/purchase.html
{% extends 'base.html' %}
{% block title %} {% if purchase %}Update Purchase{% else %}Create Purchase{% endif %} {% endblock %}
{% block content %}

<div class="page-wrapper">
  <div class="container-fluid">
    <div class="row">

  
       <div class="card">
                <form class="form-horizontal" method="POST"  action="{% url 'mart:add_purchase'  %}"
                >
                  {% csrf_token %}
                  <div class="card-body">
                    <h4 class="card-title">Purchase Record</h4>
                   
                    <div class="form-group row">  
                    <label for='role' class="col-sm-3 text-end control-label col-form-label" >Product</label>    
                    <div class="col-sm-9">
                      <select
                        class="select2 form-select shadow-none"
                        style="width: 100%; height: 36px"
                        aria-label="Product"
                        name="product"
                    
                      >
                        {% for product in product %}
                          <option value="{{product.id}}"> {{product}} {% if product.is_refill %} - Refill {% else %} - Package {% endif %}
                          </option>
                        {% endfor %}
                        </select>
                      </div>
                    </div>

                    <div class="form-group row">  
                    <label for='role' class="col-sm-3 text-end control-label col-form-label" >Supplier</label>    
                    <div class="col-sm-9">
                      <select
                        class="select2 form-select shadow-none"
                        style="width: 100%; height: 36px"
                        aria-label="Supplier"
                        name="supplier"
                    
                      >
                        {% for sup in supplier %}
                        <option value="{{sup.id}}">{{sup}}</option>
                        {% endfor %}
                      </select>
                      </div>
                    </div>
                  
                

                  
                    <div class="form-group row">
                      <label
                        for="cost"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Cost</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='cost'
                          id="cost"
                          placeholder="Product Cost Here"
                        />
                      </div>
                    </div>

                    <div class="form-group row">
                      <label
                        for="extra_cost"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Additional Cost</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='extra_cost'
                          id="extra_cost"
                          placeholder="Additional Cost Here"
                        />
                      </div>
                    </div>


                    <div class="form-group row">
                      <label
                        for="quantity"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Quantity</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='quantity'
                          id="quantity"
                          placeholder="Product Quantity Here"
                          {% if product %} value='{{product.quantity}}' {% endif %}
                        />
                      </div>
                    </div>


                   <div class="form-group row">
                    <label for="refill" class="col-sm-3 text-end control-label col-form-label">Is Refill/Warrenty</label>
                    <div class="col-sm-9" style="margin-top: 6px;">

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="customControlValidation1" name="is_refill" value="True" required>
                        <label class="form-check-label mb-0" for="customControlValidation1">Yes</label>
                      </div>

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="customControlValidation2" name="is_refill" value="False" required>
                        <label class="form-check-label mb-0" for="customControlValidation2">No</label>
                      </div>

                    </div>
                  </div>





                  <div class="border-top">
                    <div class="card-body">
                      <button type="submit" class="btn btn-primary">
                        {% if product %} Update {% else %} Add {% endif %} product
                      </button>
                    </div>
                  </div>
                </form>


    </div>
  </div>
</div>




{% endblock %}

templates/mart/purchase_record.html
{% extends 'base.html' %}
{% block title %} Purchases Record {% endblock %}
{% block content %}

<div class="page-wrapper">
<div class="container-fluid">
 <div class="card">
    <div class="card-body">
      <h5 class="card-title">Records </h5>
      <div class="table-responsive">
        <table
          id="zero_config"
          class="table table-striped table-bordered"
        >
          <thead>
            <tr>
              <th>Product Title</th>
              <th>Category</th>
              <th>Refill / Warrenty </th>
              <th>Brand</th>
              <th>Cost</th>
              <th>Extra Cost</th>
              <th>Quantity</th>
              <th>Supplier Name</th>
              <th>Supplier Address</th>
              <th>Date</th>
              <th class="col-md-1">Update</th>
              <th class="col-md-1">Delete</th>
            </tr>
          </thead>
          <tbody>
        {% for purchase in purchases %}
            <tr>
              <td>{{purchase.product.title}}</td>
              <td>{{purchase.product.category}}</td>
              <td>{% if purchase.is_refill %} Yes {% else %} No {% endif %}</td>
              <td>{{purchase.product.brand}}</td>
              <td>{{purchase.cost}}</td>
              <td>{{purchase.extra_cost}}</td>
              <td>{{ purchase.quantity }}</td>
              <td>{{purchase.supplier.contact_name}}</td>
              <td>{{purchase.supplier.address}}</td>
              <td>{{purchase.created_at}}</td>
              <td><a href="{% url 'mart:update_purchase' purchase.id %}" class="btn btn-outline-info"><i class="mdi mdi-pencil-box" style="font-size: 20px;"></i></a></td>
              <td>
              <!-- Form for the Delete button -->
              <form id="delete-form-{{ purchase.id }}" method="post" action="{% url 'mart:delete_purchase' purchase.id %}">
                {% csrf_token %}
                <button type="button" onclick="showDeleteConfirmation({{ purchase.id }})" class="btn btn-outline-info">
                  <i class="mdi mdi-delete" style="font-size: 20px;"></i>
                </button>
              </form>
            </td>
            </tr>
        {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</div>



{% endblock %}

templates/mart/return.html
{% extends 'base.html' %}
{% block title %} {% if return %}Update Return{% else %}Add Return{% endif %} {% endblock %}
{% block content %}

<div class="page-wrapper">
  <div class="container-fluid">
    <div class="row">

  
       <div class="card">
                <form class="form-horizontal" method="POST"  action="{% url 'mart:add_return'  %}"
                >
                  {% csrf_token %}
                  <div class="card-body">
                    <h4 class="card-title">Return Record</h4>
                   
                    <div class="form-group row">  
                    <label for='role' class="col-sm-3 text-end control-label col-form-label" >Purchase</label>    
                    <div class="col-sm-9">
                      <select
                        class="select2 form-select shadow-none"
                        style="width: 100%; height: 36px"
                        aria-label="purchase"
                        name="purchase"
                    
                      >
                        {% for purchase in purchase %}
                          <option value="{{purchase.id}}"> {{purchase}} {% if purchase.is_refill %} - Refill {% else %} - Package {% endif %}
                          </option>
                        {% endfor %}
                        </select>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label
                        for="quantity"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Quantity</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='quantity'
                          id="quantity"
                          placeholder="Product Quantity Here"
                          {% if product %} value='{{product.quantity}}' {% endif %}
                        />
                      </div>
                    </div>
                

                  
                    <div class="form-group row">
                      <label
                        for="cost"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Return Cost</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='return_cost'
                          id="return_cost"
                          placeholder="Return Cost Here"
                        />
                      </div>
                    </div>

                    <div class="form-group row"> 
                    <label
                        for="issue"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Return Issue</label
                      >
                    <div class="col-sm-9">
                    <textarea
                       class="form-control"
                       name="issue"
                       id="issue"
                       placeholder="Return Issue Here..."
                       style="height: 200px;"
                    ></textarea>
                    </div>
                    </div>

                  <div class="border-top">
                    <div class="card-body">
                      <button type="submit" class="btn btn-primary">
                        {% if product %} Update {% else %} Add {% endif %} Record
                      </button>
                    </div>
                  </div>
                </form>


    </div>
  </div>
</div>




{% endblock %}

templates/mart/update_product.html
{% extends 'base.html' %}
{% block title %} {% if product %}Update Product{% else %}New Product{% endif %} {% endblock %}
{% block content %}

<div class="page-wrapper">
  <div class="container-fluid">
    <div class="row">

  
       <div class="card">
                <form class="form-horizontal" method="POST" {% if product %} action="{% url 'mart:update_product' product_id=product.id %}" 
                {% else %} action="{% url 'mart:add_product'  %}" {% endif %}
                >
                  {% csrf_token %}
                  <div class="card-body">
                    <h4 class="card-title">Product Info</h4>
                    <div class="form-group row">
                      <label
                        for="title"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Title</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          id="title"
                          placeholder="Product Title Here"
                          name='title'
                          {% if product %} value='{{product.title}}' {% endif %}
                        />
                      </div>
                    </div>
                  
                    <div class="form-group row">  
                    <label for='role' class="col-sm-3 text-end control-label col-form-label" >Category</label>    
                    <div class="col-sm-9">
                      <select
                        class="select2 form-select shadow-none"
                        style="width: 100%; height: 36px"
                        aria-label="Category"
                        name="category"
                    
                      >
                        {% for cat in category %}
                        <option value="{{cat.id}}" {% if cat == prod_cat %} selected {% endif %} >{{cat}}</option>
                        {% endfor %}
                      </select>
                      </div>
                    </div>


                   <div class="form-group row">  
                    <label for='role' class="col-sm-3 text-end control-label col-form-label" >Brand</label>    
                    <div class="col-sm-9">
                      <select
                        class="select2 form-select shadow-none"
                        style="width: 100%; height: 36px"
                        aria-label="Brand"
                        name="brand"
                    
                      >
                        {% for brand in brand %}
                          <option value="{{brand.id}}" {% if brand == prod_brand %} selected {% endif %}>{{brand}}</option>
                        {% endfor %}
                        </select>
                      </div>
                    </div>

                    <div class="form-group row">
                      <label
                        for="price"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Price</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='price'
                          id="price"
                          placeholder="Product Price Here"
                          {% if product %} value='{{product.price}}' {% endif %}
                        />
                      </div>
                    </div>

                    <div class="form-group row">
                      <label
                        for="quantity"
                        class="col-sm-3 text-end control-label col-form-label"
                        >Quantity</label
                      >
                      <div class="col-sm-9">
                        <input
                          type="text"
                          class="form-control"
                          name='quantity'
                          id="quantity"
                          placeholder="Product Quantity Here"
                          {% if product %} value='{{product.quantity}}' {% endif %}
                        />
                      </div>
                    </div>


                   <div class="form-group row">
                    <label for="refill" class="col-sm-3 text-end control-label col-form-label">Is Refill / Warrenty</label>
                    <div class="col-sm-9" style="margin-top: 6px;">

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="is_refill_yes" name="is_refill" value="True" required>
                        <label class="form-check-label mb-0" for="is_refill">Yes</label>
                      </div>

                      <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="is_refill" name="is_refill" value="False" required>
                        <label class="form-check-label mb-0" for="is_refill_no">No</label>
                      </div>

                    </div>
                  </div>





                  <div class="border-top">
                    <div class="card-body">
                      <button type="submit" class="btn btn-primary">
                        {% if product %} Update {% else %} Add {% endif %} product
                      </button>
                    </div>
                  </div>
                </form>


    </div>
  </div>
</div>




{% endblock %}

templates/mart/views_return.html
{% extends 'base.html' %}
{% block title %} View Return {% endblock %}
{% block content %}

<div class="page-wrapper">
<div class="container-fluid">
 <div class="card">
    <div class="card-body">
      <h5 class="card-title">Records </h5>
      <div class="table-responsive">
        <table
          id="zero_config"
          class="table table-striped table-bordered"
        >
          <thead>
            <tr>
              <th>Product Title</th>
              <th>Issue</th>
              <th>Refill / Package </th>
              <th>Brand</th>
              <th>Product Total</th>
              <th>Return Cost</th>
              <th>Return Total</th>
              <th>Quantity</th>
              <th>Supplier Name</th>
              <th>Date</th>
              <th class="col-md-1">Update</th>
              <th class="col-md-1">Delete</th>
            </tr>
          </thead>
          <tbody>
        {% for return in return_voucher %}
            <tr>
              <td>{{return.purchase.product.title}}</td>
              <td>{{return.issue}}</td>
              <td>{% if return.purchase.is_refill %} Refill {% else %} Package {% endif %}</td>
              <td>{{return.purchase.product.brand}}</td>
              <td>{{return.returned_product_price}}</td>
              <td>{{return.return_cost}}</td>
              <td>{{return.total_return_cost}}</td>
              <td>{{ return.quantity }}</td>
              <td>{{return.purchase.supplier.contact_name}}</td>
              <td>{{return.created_at}}</td>
              <td><a href="{% url 'mart:update_return' return.id %}" class="btn btn-outline-info"><i class="mdi mdi-pencil-box" style="font-size: 20px;"></i></a></td>
              <td>
              <!-- Form for the Delete button -->
              <form id="delete-form-{{ return.id }}" method="post" action="{% url 'mart:delete_return' return.id %}">
                {% csrf_token %}
                <button type="button" onclick="showDeleteConfirmation({{ return.id }})" class="btn btn-outline-info">
                  <i class="mdi mdi-delete" style="font-size: 20px;"></i>
                </button>
              </form>
            </td>
            </tr>
        {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</div>



{% endblock %}